# Generated by Django 2.2.7 on 2019-11-25 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='ending_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='initial_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
