# Generated by Django 2.2.7 on 2019-11-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191125_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(default='HJBXVCTQJLM4', max_length=10, unique=True),
        ),
    ]
