# Generated by Django 2.2.7 on 2019-11-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191125_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(default='IIJGIRKI3I5K', max_length=10, unique=True),
        ),
    ]
