# Generated by Django 2.2.7 on 2019-11-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191127_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(default='1DL3TTBY000E', max_length=10, unique=True),
        ),
    ]
